version: '3.8'
services:
  web1:
    image: "demo:latest"
    ports:
      - "3000:3000"
    deploy:
      replicas: 3
  web2:
    image: "demo:latest"
    ports:
      - "3001:3000"
    deploy:
      replicas: 2